### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Skyrdow** [osusach/apolo-frontend#1]
- [x] Cambiar layout
- [ ] Prototipo draggable
- [ ] Prototipo de respuesta modular
- [ ] Hacer localstorage para guardar local (ux nomas)
- [ ] Landing page
- [ ] Modo invitado (poder usar la herramienta sin cuenta)
- [ ] Diseño de banco de preguntas
